#!/bin/bash
#usage ./nice.sh <file name>

file=~/Courses/c/file_handling/nice.txt

if [ $# -ne 1 ]
then
	echo -e "Usage: ./nice.sh < C - file name>"
	exit 0
fi

if [ $(find . | grep -w $1) ]
then
	vi $1
else
	cp $file $1
	vi $1
fi
